# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:47
from __future__ import unicode_literals

import contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ra', models.IntegerField(unique=True)),
                ('password', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('perfil', models.CharField(blank=True, default='A', max_length=1)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ra', models.IntegerField(unique=True)),
                ('password', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('perfil', models.CharField(blank=True, default='P', max_length=1)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ra', models.IntegerField(unique=True, verbose_name='RA')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('password', models.TextField()),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('perfil', models.CharField(default='C', max_length=1, verbose_name='Perfil')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', contas.models.UsuarioManager()),
            ],
        ),
    ]
