# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
    ]
