# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20171121_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': False},
        ),
    ]
